spree_taxon_images/config/routes.rb
Spree::Core::Engine.routes.draw do

  namespace :admin do
    resources :taxonomies do
      resources :taxons do
        resources :taxon_images
      end
    end

  end

end

spree_taxon_images/app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

spree_taxon_images/app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  has_many :taxon_images, :class_name => "Spree::TaxonImage"
end

spree_taxon_images/app/models/spree/taxon_image.rb
class Spree::TaxonImage < ActiveRecord::Base
  attr_accessible :name, :taxon_id, :icon, :image

  has_attached_file :icon,
  :styles => { :mini => '47x47>', :normal => '128x128>' },
  :default_style => :mini,
  :url => '/spree/taxons/icons/:id/:style/:basename.:extension',
  :path => ':rails_root/public/spree/taxons/icons/:id/:style/:basename.:extension',
  :default_url => '/assets/default_taxon.png'

  has_attached_file :image,
  :url => '/spree/taxons/images/:id/:style/:basename.:extension',
  :path => ':rails_root/public/spree/taxons/images/:id/:style/:basename.:extension',
  :default_url => '/assets/default_taxon.png'

  belongs_to :taxon, :class_name => "Spree::Taxon"

end

spree_taxon_images/app/controllers/spree/admin/taxon_images_controller.rb
class Spree::Admin::TaxonImagesController < Spree::Admin::ResourceController
  respond_to :html
  before_filter :load_data

  def index
    @taxon_images = @taxon.taxon_images
  end
  def create
    @taxon_image = @taxon.taxon_images.new(params[:taxon_image])
    if @taxon_image.save
      redirect_to admin_taxonomy_taxon_taxon_images_path(@taxonomy, @taxon)
    else
      respond_with(@taxon_image)
    end
  end
  def update
    @taxon_image = @taxon.taxon_images.find(params[:id])
    if @taxon_image.update_attributes(params[:taxon_image])
      redirect_to admin_taxonomy_taxon_taxon_images_path(@taxonomy, @taxon)
    else
      respond_with(@taxon)
    end
  end

  def destroy
    @taxon_image = @taxon.taxon_images.find(params[:id])

    if @taxon_image.destroy
      redirect_to admin_taxonomy_taxon_taxon_images_path(@taxonomy, @taxon)
    else
      redirect_to admin_taxonomy_taxon_taxon_images_path(@taxonomy, @taxon)
    end
  end

  private
  def load_data
    @taxonomy = Spree::Taxonomy.find(params[:taxonomy_id])
    @taxon = Spree::Taxon.find(params[:taxon_id])

  end
end

spree_taxon_images/app/helpers/spree/admin/taxon_images_helper.rb
module Spree::Admin::TaxonImagesHelper
end

spree_taxon_images/app/views/spree/admin/taxon_images/_form.html.erb
<%= f.field_container :name do %>
  <%= f.label :name, t(:name) %><br />
  <%= f.text_field :name %>
<% end %>

<%= f.field_container :icon do %>
  <%= f.label :icon, t(:icon) %><br />
  <%= f.file_field :icon %>
<% end %>

<%= f.field_container :image do %>
  <%= f.label :image, t(:image) %><br />
  <%= f.file_field :image %>
<% end %>

spree_taxon_images/app/views/spree/admin/taxon_images/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1>Editing Image</h1>

<%= render 'spree/shared/error_messages', :target => @taxon_image %>

<%= form_for [:admin, @taxonomy, @taxon, @taxon_image] , :html => { :multipart => true } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <div class="form-buttons filter-actions actions" data-hook="buttons">
   <%= button t(:update), 'icon-refresh' %>
   <span class="or"><%= t(:or) %></span>
   <%= button_link_to t(:cancel), admin_taxonomy_taxon_taxon_images_path(@taxonomy, @taxon), :icon => 'icon-remove' %>
 </div>
<% end %>

spree_taxon_images/app/views/spree/admin/taxon_images/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li>
      <p><%= button_link_to 'New Images', new_admin_taxonomy_taxon_taxon_image_url(@taxonomy, @taxon), :icon => 'add', :id => 'admin_new_asset_link' %></p>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1>Images</h1>

<table class="index" id="listing_slides" data-hook>
  <thead>
    <tr data-hook="admin_slides_index_headers">
      <th>Name</th>
      <th data-hook="admin_slides_index_header_position">URL</th>
      <th data-hook="admin_slides_index_header_actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @taxon_images.each do |item|%>
      <tr id="<%= dom_id item %>" data-hook="admin_assets_index_rows">
        <td width="150px" >
          <%= item.name %>
          <br />
          <%= image_tag item.icon.try(:url) %>

        </td>
        <td data-hook="admin_slides_index_position">
           <%= image_tag item.image.try(:url), :height => "75" %>
                     <br />
          image: <%= item.image.try(:url) %>
        </td>
        <td data-hook="admin_slides_index_row_actions">
          <%= link_to "edit", edit_admin_taxonomy_taxon_taxon_image_path(@taxonomy, @taxon, item), :class => 'edit' %> &nbsp;
          <%= link_to "delete", admin_taxonomy_taxon_taxon_image_path(@taxonomy, @taxon, item), :method => :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

spree_taxon_images/app/views/spree/admin/taxon_images/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1>New Image</h1>
<%= render 'spree/shared/error_messages', :target => @taxon_image %>

<%= form_for [:admin, @taxonomy, @taxon, @taxon_image] , :html => { :multipart => true } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <p class="form-buttons" data-hook="buttons"><%= button t(:create) %></p>
<% end %>